import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { pacifico, libre_bodoni } from "../fonts";
import clsx from "clsx";

const Pictures = () => {
  // https://bsig.s3.us-east-2.amazonaws.com/ftn/freeTheNip1.jpg
  const imageEndings = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
  ];
  return (
    <>
      {imageEndings.map((ending) => (
        <div className="carousel-item m-2" key={ending}>
          <img
            className="h-screen rounded-box"
            src={`https://bsig.s3.us-east-2.amazonaws.com/ftn/freeTheNip${ending}.jpg`}
            alt={ending}
          />
        </div>
      ))}
    </>
  );
};

const Home: NextPage = () => {
  return (
    <html data-theme="dracula">
      <Head>
        <title>BSIG</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx("bg-black", libre_bodoni.className)}>
        <div className="min-h-screen w-full bg-gradient-to-br from-red-400/40 from-20% via-blue-400/40 via-40% to-violet-400/40 p-0">
          <div
            className="hero min-h-screen"
            style={{
              backgroundImage: `url("https://bsig.s3.us-east-2.amazonaws.com/default/mainBackground.jpg")`,
            }}
          >
            <div className="hero-overlay bg-opacity-60"></div>
            <div className="hero-content text-center text-neutral-content">
              <div className="max-w-md">
                <h1 className="font-serif text-5xl text-white sm:text-[5rem]">
                  Brayden Singley is{" "}
                  <span className={clsx("text-accent", pacifico.className)}>
                    G
                  </span>
                  <span className={clsx("text-secondary", pacifico.className)}>
                    A
                  </span>
                  <span className={clsx("text-primary", pacifico.className)}>
                    Y
                  </span>
                </h1>
              </div>
            </div>
          </div>
          <div className="">
            <div className="carousel w-full p-2">
              <Pictures />
            </div>
          </div>
        </div>
      </main>
    </html>
  );
};

export default Home;
